### PR TITLE
Add Modpack Age of Engineering to the server

### PR DESCRIPTION
**Pull request by StripedMonkey**
I added the "Minecraft" folder which contains everything needed in terms of mods and configuration. It also needs Forge version 12.18.3.2511 or greater.

### CODE REVIEW

**Comment by egee-irl** [comment]
@StripedMonkey change the target repo of this to ``egeeio`` pls

**Comment by StripedMonkey** [comment]
I'm not sure I follow, you want me to put it in egee-irl/egeeio?

**Comment by egee-irl** [comment]
Yeah, I created a new branch called egeeio - https://github.com/egee-irl/gsc-minecraft-modded/tree/egeeio

Point this PR at that branch instead of unstable

**Comment by StripedMonkey** [comment]
:thumbsup: Done!

**Pull request merged**
